services:
  server:
    container_name: backend
    build: ./backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:5001"
    restart: always

  client:
    container_name: frontend
    build: ./frontend
